services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: dockerfile.backend
    ports:
      - "3010:3010"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
